### ISSUE TITLE
报名优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/rank#19]
## 选择团队优化
团队名称后 增加 `(ID:xxx)`

- [x] 已完成

**Comment by iRuxu** [comment]
## 报名公告
样式优化
增加报名后删除团队情况的处理说明

- [x] 已完成

**Comment by iRuxu** [comment]
## 判断是否已报名
不进行UI跳转，继续禁用报名按钮，并额外添加已报名提示

- [x] 已完成

**Comment by iRuxu** [comment]
## 4k适配

- [x] 已完成

**Comment by M-ls** [comment]
## 判断报名状态
当前存在：报名后未审核提示
![image](https://user-images.githubusercontent.com/36070993/166113311-97eef2ce-4ea1-4409-9caf-60a63e6e67ed.png)
实际上未成功报名
在此状态下可继续报名导致同时报名两个团队
![AO1NA)PTMVQI74U0%DT 8V](https://user-images.githubusercontent.com/36070993/166113285-f42c150a-1156-47e4-a68e-733df0b5e9b0.png)
需要在未审核时候返回未审核状态
审核后返回报名成功状态
