### ISSUE TITLE
百强榜时间线

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/rank#41]
<img width="493" alt="image" src="https://github.com/JX3BOX/rank/assets/8476969/f61521ab-e134-4eb2-b82f-b28d89029da3">

具体设计资源联系 冰块

- [x] 已完成

**Comment by zixuan1986** [comment]
https://js.design/f/zyXNO5?p=15rK2dcaFd&mode=design

![image](https://github.com/JX3BOX/rank/assets/40552272/a7166379-9f82-49ae-b644-87566451ffaa)

- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="1279" alt="image" src="https://github.com/JX3BOX/rank/assets/40552272/1ce02cd7-66eb-4956-98fd-cd007d659512">
这个当前进度应该是进入时就默认在最中间，根据当前时间来定位与现在时间最近的节点，并显示在最中心

- [x] 已完成

**Comment by zixuan1986** [comment]
时间轴下方的文字是按实际情况来填写的，所以需要不固定宽度，然后移动就按他当前的文字宽度加间距移动
- [x] 已完成

当前进度往前的菱形应该都是实心的，相当于已勾选/完成
- [x] 已完成

箭头放在时间线上方会不会好一点？.m-time-shaft-swiper-box距上方20px
- [x] 已完成

**Comment by iRuxu** [comment]
- [ ]
