### ISSUE TITLE
百强跨服

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/rank#43]
<img width="413" alt="image" src="https://github.com/JX3BOX/rank/assets/8476969/e8334196-6528-4886-b301-18e52d236463">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="486" alt="image" src="https://github.com/JX3BOX/rank/assets/8476969/bcc37ea5-8643-4a57-a111-bb2f52e13981">

<img width="1915" alt="image" src="https://github.com/JX3BOX/rank/assets/8476969/f86644b1-9170-403e-9f38-ec8276fee901">

工作量统计也换到编辑部

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1455" alt="image" src="https://github.com/JX3BOX/rank/assets/8476969/0cdf3cb5-9514-4786-9511-8856c65ff8d4">

- [ ] 已完成

**Comment by Kaviilee** [comment]
> <img alt="image" width="1455" src="https://private-user-images.githubusercontent.com/8476969/326316525-0cdf3cb5-9514-4786-9511-8856c65ff8d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzM0MzUsIm5iZiI6MTcxNDM3MzEzNSwicGF0aCI6Ii84NDc2OTY5LzMyNjMxNjUyNS0wY2RmM2NiNS05NTE0LTQ3ODYtOTUxMS04ODU2YzY1ZmY4ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDY0NTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI4OWJjOTg0OWE2ZTQxMGRjMzk2MTU1N2VlMWVkZmQ2YmVhN2ZlNmU5MmFkMWExM2VlYmFhYjgxOTFhMGJlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Io781-8BpOTdSnWylYxONok2KXq_NRwyBeTC6y9Sw_I">
> * [ ]  已完成

应该是接口返回的问题，已经报给胡哥
