### ISSUE TITLE
天团规则与简介

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/rank#49]
## 后端：小胡
<img width="1346" alt="image" src="https://github.com/JX3BOX/rank/assets/8476969/41698161-a30d-4d0a-802b-483e99297723">

加字段

- [x] 已完成

**Comment by iRuxu** [comment]
## 后台前端：朱砂

<img width="1097" alt="image" src="https://github.com/JX3BOX/rank/assets/8476969/8b06562d-d044-4c0e-a44d-53c52fb08167">

前端专题渲染拿对应字段即可

- [x] 已完成

**Comment by flyflyknife** [comment]
以增加字段到curd接口
