### ISSUE TITLE
小程序·第九届秘境百强榜

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/rank#55]
## 概述

小程序百强分2个页面
一个是投票的【先做】
一个是看排行榜的
已经初始化好了

![QQ_1729413429799](https://github.com/user-attachments/assets/1c2e1d24-1d7c-4ff7-b93e-e659cce8b434)

- [x] 已完成

**Comment by iRuxu** [comment]
## 设计稿

https://js.design/f/zyXNO5?p=mKo6QV8OpQ&mode=design&linkelement=133-1287

![de636195a5f439f805c2d3f314adabbf](https://github.com/user-attachments/assets/4cb0a215-0811-45ab-b686-02be04cb23f5)



- [x] 已完成

**Comment by Kaviilee** [comment]
## 验收
1. 页面的元素间距需要确认一下

- [x] 已完成

2. 页面分享记得加上，可以参考中秋的
![QQ_1729861676302](https://github.com/user-attachments/assets/0eca8376-40b5-4e50-8ca7-04395c622b03)

- [x] 已完成
3. 特殊样式需要调节，你这个详情按钮显示被撑过去的。短的团队名反而缩过去了
![QQ_1729861858100](https://github.com/user-attachments/assets/cd059224-3e7e-4698-a5ba-b653de4fca59)
