### ISSUE TITLE
福利申请优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/rank#57]
<img width="345" alt="image" src="https://github.com/user-attachments/assets/5d2b6394-a3bf-49a3-9270-21837e6cfa6d">

**Comment by iRuxu** [comment]
<img width="314" alt="image" src="https://github.com/user-attachments/assets/67741946-faf3-46b9-b86e-35b1439bbf92">

<img width="309" alt="image" src="https://github.com/user-attachments/assets/7593efa7-50a3-4b9c-9bb2-f1ea93498c03">

你宽度可以更大一些，以和现在适配

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="373" alt="image" src="https://github.com/user-attachments/assets/998696c7-1d89-4485-8475-0fd408491ab8">

找冰块要一下美术资源

- [x] 已完成

**Comment by yu-minggang** [comment]
> <img alt="image" width="314" src="https://private-user-images.githubusercontent.com/8476969/369604105-67741946-faf3-46b9-b86e-35b1439bbf92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDk1MzAsIm5iZiI6MTcyNzAwOTIzMCwicGF0aCI6Ii84NDc2OTY5LzM2OTYwNDEwNS02Nzc0MTk0Ni1mYWYzLTQ2YjktYjg2ZS0zNWIxNDM5YmJmOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTI0NzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNkM2FlMTdkOWE2NGFlOTFjZjAyZmZkZGM0OTI5NDZiNTA4NDI2ZDE0NzcxNDNlNTM3N2E3YTgwNjI0ZDJjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Jmt4ZpZBE3_wDDOr6Xa70K4TiM9ObpOPBUv9WcuIVyU"> <img alt="image" width="309" src="https://private-user-images.githubusercontent.com/8476969/369604111-7593efa7-50a3-4b9c-9bb2-f1ea93498c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDk1MzAsIm5iZiI6MTcyNzAwOTIzMCwicGF0aCI6Ii84NDc2OTY5LzM2OTYwNDExMS03NTkzZWZhNy01MGEzLTRiOWMtOWJiMi1mMWVhOTM0OThjMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTI0NzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg3MDc4OTM1ZjM4YWJhMmM1ZThlMGU1ZmJlYzc2NzFmZWJhMTEyY2ZjNzFkMDVlYWE5NjYxY2E2YmZhODAxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z2ud00DQM2SfkycizRBUZp668bPVCkOjIWcg391RDpY">
> 你宽度可以更大一些，以和现在适配
> 
> * [ ]  已完成

宽度加大了，和百强的格式相接近，边框暂时没加
